#!/bin/bash
java_v='command -v java'
if [[ "$java_v" == null ]]; then
    read -p "Java is not found. Install? [Y/N] " input
    input=$(echo "$input" | tr '[:lower:]' '[:upper:]')
    if [[ "$input" == "Y" ]]; then
        echo "Installing..."
        brew_v='command -v brew'
        if "$brew_v" == null ; then
            #echo executed brew install java21
            brew install java21
        else
            read -p "Brew is not found. Install? [Y/N] " input_1
            input_1=$(echo "$input_1" | tr '[:lower:]' '[:upper:]')
            if [[ "$input_1" == "Y" ]]; then
                echo "Installing Brew..."
                /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
                brew install java
            else
                echo "Exiting program: No Brew installed on the system."
                exit
            fi
        fi
    else
        echo "Exiting program: No Java installed on the system."
        exit
    fi
fi
cd "$(dirname "$0")"
java -jar CompSci_Prj*.jar